### ISSUE TITLE
Perhaps you could look at this project too

### ISSUE THREAD

**Issue by NeuronSooup** [lime-desu/dootsfile#2]
Hello, what a great gnome shell you have created, there are clearly a lack of good gnome 42 shells. I was wondering if you want to look at my own gnome 42 shell project, which closely resembles yours but with the shell looking a little but rounded and consistent in my taste. However, I still don't know how to do the color correctly which make the color of some elements looking not as consistent.

This is the project: https://github.com/NeuronSooup/Gnome-topbar-le-dots
I barely know how to do css or color schemes but I tried to make the best that I can, I hope you can further improve the consistency of the color. 

Thank you!

**Comment by Ioulan** [comment]
Thank you very much!
Hi, to be honest, I'm not that good at CSS either, and if you look at my gnome shell, it contains almost 5000+ lines, making it hard for me to maintain just looking at it make me feel dizzy. Additionally, I didn't create any of it; all credit for that goes to MonoTheme Gtk; If you view my git history I didn't do that much It's just a copy of MonoTheme with a custom color values.

I'm sorry, but I don't want to bother with gnome-shell that much, it is a pain in the ass, And I have my bugs too which I'm not bothered to fix it.

https://user-images.githubusercontent.com/114978689/218258197-4c49f13d-bb8a-483c-ae30-9d1a977cad47.mp4

But I do suggest using this extension for ease of debugging and targeting CSS properties ([looking glass button](https://extensions.gnome.org/extension/2296/looking-glass-button/))
![Screenshot from 2023-02-11 20-27-48](https://user-images.githubusercontent.com/114978689/218258325-e0ca5d4f-7956-44cc-8d5d-114c562d4f09.png)

Andalso If you know [Gradience](https://github.com/GradienceTeam/Gradience) on their next major release you can now easily modify gnome-shell (on v0.8)

**Comment by NeuronSooup** [comment]
Thank you for considering
